expm1 removed from dust analytic expression
Sympy did not interpret it as symbol and therefore the analytic
differentiation did not work. It was causing:

NameError: global name 'Derivative' is not defined

or

NameError: global name 'Subs' is not defined